name: C++ CI

on: [push, pull_request]

env:
  VCPKG_DIR: ./vcpkg
  VCPKG_TRIPLET: x64-windows
  KAFKA_VERSION: 3.6.1
  KAFKA_DIR: kafka_2.13-3.6.1

jobs:
  windows-build:
    name: Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'

     # - name: Install vcpkg
     #   run: |
     #     git clone https://github.com/microsoft/vcpkg $env:VCPKG_DIR
     #     & "$env:VCPKG_DIR\bootstrap-vcpkg.bat"
     #     echo "$env:VCPKG_DIR" >> $env:GITHUB_PATH

     # - name: Install dependencies
     #   run: vcpkg install librdkafka --triplet $env:VCPKG_TRIPLET

      - name: Download and prepare Kafka
        shell: pwsh
        run: |
            $kafka_version = "3.6.1"
            $archive_name = "kafka_2.13-$kafka_version.tgz"
            $extracted_dir = "kafka_2.13-$kafka_version"
            $target_dir = "kafka"

            Write-Host "Tar version:"
            tar --version

            # Скачивание архива
            Invoke-WebRequest "https://archive.apache.org/dist/kafka/$kafka_version/$archive_name" -OutFile kafka.tgz

            # Создание директории для распаковки
            New-Item -ItemType Directory -Name $target_dir -Force | Out-Null

            # Распаковка архива
            tar -xzf kafka.tgz -C $target_dir --strip-components 1

            # После распаковки
            Write-Host "Directory contents:"
            Get-ChildItem -Path $target_dir -Recurse | Format-Table -AutoSize

            # Проверка успешности распаковки
            if (-Not (Test-Path "$target_dir\bin\windows\kafka-server-start.bat")) {
                Write-Error "Kafka files not extracted properly!"
                Get-ChildItem -Path $target_dir -Recurse | Format-List
                exit 1
            }

            # Настройка конфигурации
            Set-Location $target_dir
    
            $config_path = "config\kraft\server.properties"
            $config = Get-Content $config_path -Raw
    
            # Модификация конфигурации
            $config = $config -replace '(?m)^process.roles=.*', 'process.roles=broker,controller'
            $config = $config -replace '(?m)^node.id=.*', 'node.id=1'
            $config = $config -replace '(?m)^controller.quorum.voters=.*', 'controller.quorum.voters=1@localhost:9093'
            $config = $config -replace '(?m)^listeners=.*', 'listeners=PLAINTEXT://:9092,CONTROLLER://:9093'
            $config = $config -replace '(?m)^advertised.listeners=.*', 'advertised.listeners=PLAINTEXT://localhost:9092'
            $config = $config -replace '(?m)^log.dirs=.*', 'log.dirs=logs'
    
            Set-Content $config_path $config

            # Инициализация хранилища
            $cluster_id = .\bin\windows\kafka-storage.bat random-uuid
            .\bin\windows\kafka-storage.bat format -t $cluster_id -c $config_path

            Set-Location ..

      - name: Configure CMake
        run: |
          cmake -B build -S . -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_DIR/scripts/buildsystems/vcpkg.cmake"

      - name: Build the project
        run: cmake --build build --config Release

      - name: Start Kafka Server
        run: |
          cd $env:KAFKA_DIR
          Start-Process -NoNewWindow -FilePath ".\bin\windows\kafka-server-start.bat" -ArgumentList ".\config\kraft\server.properties" -PassThru | Select-Object -ExpandProperty Id | Out-File -FilePath kafka.pid
          Start-Sleep -Seconds 25

      - name: Create test topic
        run: |
          cd $env:KAFKA_DIR
          .\bin\windows\kafka-topics.bat --create --topic testtopic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1


      - name: Run tests
        working-directory: build
        run: ctest -VV --test-dir Test --build-config Release

      - name: Stop Kafka Server
        if: always()
        run: |
          Get-Content $env:KAFKA_DIR\kafka.pid | ForEach-Object { Stop-Process -Id $_ -Force }

  linux-build:
    name: Ubuntu x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make librdkafka-dev openjdk-17-jdk

      - name: Download and prepare Kafka
        run: |
          wget https://archive.apache.org/dist/kafka/3.6.1/kafka_2.13-3.6.1.tgz
          tar -xzf kafka_2.13-3.6.1.tgz
          cd kafka_2.13-3.6.1
          KAFKA_CLUSTER_ID=$(bin/kafka-storage.sh random-uuid)
          bin/kafka-storage.sh format -t $KAFKA_CLUSTER_ID -c config/kraft/server.properties
          sed -i 's/^process.roles=.*/process.roles=broker,controller/' config/kraft/server.properties
          sed -i 's/^node.id=.*/node.id=1/' config/kraft/server.properties
          sed -i 's/^controller.quorum.voters=.*/controller.quorum.voters=1@localhost:9093/' config/kraft/server.properties
          sed -i 's/^listeners=.*/listeners=PLAINTEXT:\/\/:9092,CONTROLLER:\/\/:9093/' config/kraft/server.properties
          sed -i 's/^advertised.listeners=.*/advertised.listeners=PLAINTEXT:\/\/localhost:9092/' config/kraft/server.properties
          sed -i 's/^log.dirs=.*/log.dirs=\/tmp\/kraft-combined-logs/' config/kraft/server.properties

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --parallel 4

      - name: Start Kafka Server
        run: |
          cd kafka_2.13-3.6.1
          nohup bin/kafka-server-start.sh config/kraft/server.properties > /tmp/kafka.log 2>&1 &
          echo $! > /tmp/kafka.pid
          sleep 15

      - name: Create test topic
        run: |
          cd kafka_2.13-3.6.1
          bin/kafka-topics.sh --create --topic testtopic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1

      - name: Run tests
        working-directory: build
        run: ctest -VV --test-dir Test --build-config Release

      - name: Stop Kafka Server
        if: always()
        run: |
          kill $(cat /tmp/kafka.pid) || true
          sleep 5