name: C++ CI

on: [push, pull_request]

env:
  VCPKG_DIR: ./vcpkg  # Путь относительно рабочей директории
  VCPKG_TRIPLET: x64-windows

jobs:
  windows-build:
    name: Windows x64
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg $env:VCPKG_DIR
          & "$env:VCPKG_DIR\bootstrap-vcpkg.bat"
          echo "$env:VCPKG_DIR" >> $env:GITHUB_PATH

      - name: Install dependencies
        run: vcpkg install librdkafka --triplet $env:VCPKG_TRIPLET

      - name: Configure CMake
        run: |
          cmake -B build -S . -A x64 `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_DIR/scripts/buildsystems/vcpkg.cmake"

      - name: Build the project
        run: cmake --build build --config Release

      - name: Run tests
        working-directory: build
        run: ctest -VV --test-dir Test --build-config Release


  linux-build:
    name: Ubuntu x64
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: bitnami/zookeeper:3.8
        ports: ["2181:2181"]
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
      kafka:
        image: bitnami/kafka:3.4
        ports: ["9092:9092"]
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: "yes"
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make librdkafka-dev

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --parallel 4

      - name: Wait for Kafka
        run: |
          for i in {1..10}; do
            nc -zv localhost 9092 && exit 0
            sleep 5
          done
          exit 1

      - name: Run tests
        working-directory: build
        run: ctest -VV --test-dir Test --build-config Release